server:
  port: 9081
  http:
    port: 8081
  servlet:
    context-path: /eir
  ssl:
    enabled: true
    key-alias: dmc_eir_ssl
    key-store: classpath:dmc_eir.p12
    key-store-type: PKCS12
    key-password: eir@12345
    key-store-password: ENC(JM+vF0m1pHbWwTljIPg9sBzTy5YMye0v)

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/app
    username: root
    password: ENC(jxNzi7e8T94AnHUxgizmuQ==)
    #    url: jdbc:mysql://159.223.159.153:3306/ceir
    #    username: cdrp
    #    password: Cdrp@1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    #properties:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

alerts:
  postUrl: http://10.100.2.231:9504/eirs/alert
  processId: Provisioning Module
  alerts-mapping:
    CORE_MODULE_URL_CALL_EXCEPTION:
      alertId: ALERT1001
      message: "Not able to call CORE Module, <URL> : <EXCEPTION>."

scheduler:
  daily:
    cronjob: 0 0 1 * * *

deviceSyncRequest:
  delete:
    beforeDays: 5
    filePath: D:/


jasypt:
  encryptor:
    password: eir
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator