package com.eir.pgm.repository.entity;

public interface SystemConfigKeys {

    String PGM_NO_OF_INSTANCES = "PGM_NO_OF_INSTANCES";

    String PGM_INSTANCE = "PGM_INSTANCE_NO_<NUMBER>";

    String INSTANCE_TPS = "PGM_INSTANCE_<INSTANCE_NAME>_TPS";

    Integer DEFAULT_INSTANCE_TPS = 10;


    String INSTANCE_URL_READ_TIME_OUT = "PGM_INSTANCE_<INSTANCE_NAME>_READ_TIME_OUT";

    String INSTANCE_URL_EXCEPTION = "PGM_INSTANCE_<INSTANCE_NAME>_EXCEPTION_LIST_URL";

    String INSTANCE_URL_TRACKED = "PGM_INSTANCE_<INSTANCE_NAME>_TRACKED_LIST_URL";

    String INSTANCE_URL_BLACKED = "PGM_INSTANCE_<INSTANCE_NAME>_BLACKED_LIST_URL";

    String INSTANCE_URL_ALLOWED_TAC = "PGM_INSTANCE_<INSTANCE_NAME>_ALLOWED_TAC_URL";

    String INSTANCE_URL_BLOCKED_TAC = "PGM_INSTANCE_<INSTANCE_NAME>_BLOCKED_TAC_URL";

    String INSTANCE_URL_HLR_DATA = "PGM_INSTANCE_<INSTANCE_NAME>_HLR_DATA_URL";

    String INSTANCE_URL_GSMA_DATA = "PGM_INSTANCE_<INSTANCE_NAME>_GSMA_DATA_URL";
}
